### ISSUE TITLE
Permissions on gpio not set by default. Add to instructions note do a gpio export?

### ISSUE THREAD

**Issue by rodtoll** [benlamonica/homebridge-rasppi-gpio-garagedoor#1]
By default on the raspberry pi (at least it was on mine) none of the pins are exported. This means that without the user updating their system configuration your plugin fails as the gpio pins haven't been exported.

For me I needed to add the following to /etc/rc.local file. My homebridge runs as the pi user. Need to replace pi with the user being used to run homebridge.
sudo -u pi /usr/local/bin/gpio export 26 out
sudo -u pi /usr/local/bin/gpio export 24 in

(Pin 26 was my output pin, 24 was my input pin).

I am happily opening my garage door now -- thank you.

**Comment by benlamonica** [comment]
Good point. I'll add instructions to the readme and sample rc.d files. Glad it's working for you :)
