### ISSUE TITLE
simply open a gate

### ISSUE THREAD

**Issue by tigroz** [benlamonica/homebridge-rasppi-gpio-garagedoor#20]
hi, sorry for my English,
I have to open 2 gates with raspberry pi connected to a relay.
The relay is connected to the remote control and when it closes the contacts starts the pulse. I would like to use this plugin but do not know how to set up the garage-door-gpio script also not needing the sensors for closed door and open door, can i completely eliminate them from config.json?
ok just resolved, never mind...

**Comment by benlamonica** [comment]
@tigroz Yes, just remove them if you don't have them. Sorry, I'll make that more clear in the instructions.
