### ISSUE TITLE
Further developing the script

### ISSUE THREAD

**Issue by varna33** [benlamonica/homebridge-rasppi-gpio-garagedoor#24]
Hi,

I would like to develop to script more completely with two relays & two relay sensors for garage door, and add one relay for the gate.

I have two relays for garage door and would like to mange the door more specifically through them:
1. Action (1 second high duration) - Close door
2. Action (1 second high duration) - Open door

I have two relay sensors giving status from the garage door, and would like to sense the door status specifically through them:
1. Status - Door is closed
2. Status - Door is open

Also I have relay to manage the gate:
1. Action (1 second high duration) - Open the gate
The gate is closing after few minutes automatically, if not blocked permanently with 2. Action
2. Action (keep high) - Block the gate open

Would highly appreciate your advise how to develop and complete the script to manage this more granular set-up.

Janis

**Comment by benlamonica** [comment]
@varna33 The plugin already supports 2 sensors to detect when the door is open or closed. If you want to have 2 relays to control opening and closing the door, then it's pretty simple to just add another relay pin and call that pin only for opening. Please submit a PR if you'd like to include these enhancements in the future. As I don't have that particular setup, I'm not able to test, so I'm not planning on making this particular change.
