### ISSUE TITLE
Plugin and Eve Door/Window Sensor communication

### ISSUE THREAD

**Issue by GatoPharaoh** [benlamonica/homebridge-rasppi-gpio-garagedoor#31]
Hi

I'm using an Elgato Eve Door and Window Sensor (which is HomeKit capable) to determine if my garage is open or closed.
Any idea how to implement the state of the Eve Sensor into the plugin. So that the plugin switch knows from the Eve sensor when my garage is opened or closed?

I thought about something like a second switch from the plugin which is just there to tell the plugin if the door is opened or closed. The second switch would be triggered by the eve door sensor via automation. Is this possible?

Thanks in advance

**Comment by benlamonica** [comment]
Just brainstorming here, but maybe you could write a program to run on your raspberry pi that flips the state of a GPIO when the garage door is open/closed and then you can use the garagedoor plugin as is. Or you can modify the garagedoor plugin to query a different file which contains the state. Or you could just buy the $4 reed switch and hook it up and have 2 different door open sensors.

**Comment by GatoPharaoh** [comment]
awesome input - thank you!
