### ISSUE TITLE
Homebridge not starting

### ISSUE THREAD

**Issue by jabba243** [benlamonica/homebridge-rasppi-gpio-garagedoor#49]
Anyone having issues with Geek Slant Smart Garage since updating to iOS 13? My setup was working fine until 13 then iPhone would respond  by stating “you have more than one garage door. Ask me again with a specific room or device name”. This is after I’ve asked for Siri to open/close right garage door. I’ve rebooted rpi and deleted the bridge from my phone and now can’t find it again. Now I get this error. 

<img width="1024" alt="Screenshot 2019-11-09 at 19 23 40" src="https://user-images.githubusercontent.com/12376522/68538911-c58aff80-03e0-11ea-81b8-e31d10c64ad8.png">

**Comment by SK8081** [comment]
I am having this same issue.  Did you ever get an answer?  If I remove the closed sensor setting in my config.json, homebridge will run fine.  As soon as I place the setting back in the file, I get teh same error as above.

**Comment by jabba243** [comment]
Not really. I ended up starting again with fresh install/setup. Fixed the issue in the debug but not the error where Siri was asking for more info on which door to open. Then I noticed that what my Apple Watch was hearing was different to what I was saying. Example if I said “open right garage door” Siri would hear “open a right garage door” thenI would get the response of “you have more than one garage door....”.  I have figured out how to fix that. Seems a Siri or watch issue more than the geek slant software.

**Comment by jabba243** [comment]
* I haven’t figured out how to fix that.

**Comment by toshibochan** [comment]
Now I’m using this! Take look
https://github.com/dubocr/homebridge-gpio-device

**Comment by SK8081** [comment]
Thanks.  I guess this isn't supported any more.  I will move to your suggested add on

**Comment by albliu** [comment]
got this working yesterday. for me, i had to make sure homebridge calls the garage-door-gpio start script on start up. "see the step 3 in readme.md""

I had to manually edit the exisiting homebridge.service file though, instead of copying it over from the project, because i was running raspian set up from https://github.com/homebridge/homebridge-raspbian-image/wiki/Getting-Started, and they had a homebridge.service already

**Comment by benlamonica** [comment]
Sorry, I got a new garage door that doesn't have a simple mechanism, and just don't have time support the project.
