### ISSUE TITLE
door lock

### ISSUE THREAD

**Issue by toshibochan** [benlamonica/homebridge-rasppi-gpio-garagedoor#6]
hi @benlamonica i have a big request!!!!!
if possible you can make homebridge for door lock using servo. instead relay will use servo or stepped motor and little limit switches for know lock or unlock. plus one button to open and close manually and led green and red for know status.
thanks

**Comment by benlamonica** [comment]
I don't have anyway to test this, nor do I have a lock on my garage door that I have a need to automate. If you're willing to do the dev work yourself, go ahead and submit a PR (you can clone this repo and check it out on your raspberry pi, and then run npm link in the directory, and then your homebridge will use the local version).
