### ISSUE TITLE
can you change pin for sensor to closed=LOW, open=HIGH

### ISSUE THREAD

**Issue by omarcin31** [benlamonica/homebridge-rasppi-gpio-garagedoor#7]
this is default setup:
The GPIO pin that senses if the door is closed (Closed = HIGH, Open = LOW)
i would like to change it to:
The GPIO pin that senses if the door is closed (Closed = LOW, Open = HIGH)

**Comment by toshibochan** [comment]
this is may setup!!
[garage-door-gpio.zip](https://github.com/benlamonica/homebridge-rasppi-gpio-garagedoor/files/419174/garage-door-gpio.zip)

**Comment by benlamonica** [comment]
This has now been fixed as of version 1.0.3 or later.
